### ISSUE TITLE
`npm run package` fails in a local run

### ISSUE THREAD

**Issue by HighCommander4** [clangd/vscode-clangd#931]
I'm getting errors when trying to build latest vscode-clangd trunk locally:

```
$ npm run package

> vscode-clangd@0.4.0 package
> vsce package --baseImagesUrl https://raw.githubusercontent.com/clangd/vscode-clangd/master/

Executing prepublish script 'npm run vscode:prepublish'...

> vscode-clangd@0.4.0 vscode:prepublish
> npm run check-ts && npm run esbuild -- --minify --keep-names


> vscode-clangd@0.4.0 check-ts
> tsc -noEmit -p ./

api/node_modules/vscode-jsonrpc/lib/common/linkedMap.d.ts:28:5 - error TS2416: Property 'forEach' in type 'LinkedMap<K, V>' is not assignable to the same property in base type 'Map<K, V>'.
  Type '(callbackfn: (value: V, key: K, map: LinkedMap<K, V>) => void, thisArg?: any) => void' is not assignable to type '(callbackfn: (value: V, key: K, map: Map<K, V>) => void, thisArg?: any) => void'.
    Types of parameters 'callbackfn' and 'callbackfn' are incompatible.
      Types of parameters 'map' and 'map' are incompatible.
        Type 'LinkedMap<K, V>' is not assignable to type 'Map<K, V>'.
          The types returned by 'entries()' are incompatible between these types.
            Property '[Symbol.dispose]' is missing in type 'IterableIterator<[K, V]>' but required in type 'MapIterator<[K, V]>'.

28     forEach(callbackfn: (value: V, key: K, map: LinkedMap<K, V>) => void, thisArg?: any): void;
       ~~~~~~~

  node_modules/typescript/lib/lib.esnext.disposable.d.ts:36:5
    36     [Symbol.dispose](): void;
           ~~~~~~~~~~~~~~~~~~~~~~~~~
    '[Symbol.dispose]' is declared here.

api/node_modules/vscode-jsonrpc/lib/common/linkedMap.d.ts:29:5 - error TS2416: Property 'keys' in type 'LinkedMap<K, V>' is not assignable to the same property in base type 'Map<K, V>'.
  Type '() => IterableIterator<K>' is not assignable to type '() => MapIterator<K>'.
    Property '[Symbol.dispose]' is missing in type 'IterableIterator<K>' but required in type 'MapIterator<K>'.

29     keys(): IterableIterator<K>;
       ~~~~

  node_modules/typescript/lib/lib.esnext.disposable.d.ts:36:5
    36     [Symbol.dispose](): void;
           ~~~~~~~~~~~~~~~~~~~~~~~~~
    '[Symbol.dispose]' is declared here.

api/node_modules/vscode-jsonrpc/lib/common/linkedMap.d.ts:30:5 - error TS2416: Property 'values' in type 'LinkedMap<K, V>' is not assignable to the same property in base type 'Map<K, V>'.
  Type '() => IterableIterator<V>' is not assignable to type '() => MapIterator<V>'.
    Property '[Symbol.dispose]' is missing in type 'IterableIterator<V>' but required in type 'MapIterator<V>'.

30     values(): IterableIterator<V>;
       ~~~~~~

  node_modules/typescript/lib/lib.esnext.disposable.d.ts:36:5
    36     [Symbol.dispose](): void;
           ~~~~~~~~~~~~~~~~~~~~~~~~~
    '[Symbol.dispose]' is declared here.

api/node_modules/vscode-jsonrpc/lib/common/linkedMap.d.ts:31:5 - error TS2416: Property 'entries' in type 'LinkedMap<K, V>' is not assignable to the same property in base type 'Map<K, V>'.
  Type '() => IterableIterator<[K, V]>' is not assignable to type '() => MapIterator<[K, V]>'.
    Property '[Symbol.dispose]' is missing in type 'IterableIterator<[K, V]>' but required in type 'MapIterator<[K, V]>'.

31     entries(): IterableIterator<[K, V]>;
       ~~~~~~~

  node_modules/typescript/lib/lib.esnext.disposable.d.ts:36:5
    36     [Symbol.dispose](): void;
           ~~~~~~~~~~~~~~~~~~~~~~~~~
    '[Symbol.dispose]' is declared here.

api/node_modules/vscode-jsonrpc/lib/common/linkedMap.d.ts:32:5 - error TS2416: Property '[Symbol.iterator]' in type 'LinkedMap<K, V>' is not assignable to the same property in base type 'Map<K, V>'.
  Type '() => IterableIterator<[K, V]>' is not assignable to type '() => MapIterator<[K, V]>'.
    Property '[Symbol.dispose]' is missing in type 'IterableIterator<[K, V]>' but required in type 'MapIterator<[K, V]>'.

32     [Symbol.iterator](): IterableIterator<[K, V]>;
       ~~~~~~~~~~~~~~~~~

  node_modules/typescript/lib/lib.esnext.disposable.d.ts:36:5
    36     [Symbol.dispose](): void;
           ~~~~~~~~~~~~~~~~~~~~~~~~~
    '[Symbol.dispose]' is declared here.


Found 5 errors in the same file, starting at: api/node_modules/vscode-jsonrpc/lib/common/linkedMap.d.ts:28

 ERROR  npm failed with exit code 2
```

`git bisect` shows that the errors were first introduced by https://github.com/clangd/vscode-clangd/commit/ed8b5cb05d83ea73e7e0a2df8ac88acd1c02a7d4.

@tamird do you know what is causing these errors?

**Comment by tamird** [comment]
Looks like https://github.com/microsoft/vscode-languageserver-node/issues/1590 / https://github.com/microsoft/vscode-languageserver-node/pull/1644.

But I just ran this locally and it finished without error on a fresh checkout
```
vscode-clangd % npm run package

> vscode-clangd@0.4.0 package
> vsce package --baseImagesUrl https://raw.githubusercontent.com/clangd/vscode-clangd/master/

Executing prepublish script 'npm run vscode:prepublish'...

> vscode-clangd@0.4.0 vscode:prepublish
> npm run check-ts && npm run esbuild -- --minify --keep-names


> vscode-clangd@0.4.0 check-ts
> tsc -noEmit -p ./


> vscode-clangd@0.4.0 esbuild
> esbuild ./src/extension.ts --bundle --outfile=out/bundle.js --external:@aws-sdk/client-s3 --external:vscode --format=cjs --platform=node --minify --keep-names


  out/bundle.js  1007.8kb

⚡ Done in 27ms
 WARNING  LICENSE, LICENSE.md, or LICENSE.txt not found
Do you want to continue? [y/N] y
 INFO  Files included in the VSIX:
vscode-clangd-0.4.0.vsix
├─ [Content_Types].xml 
├─ extension.vsixmanifest 
└─ extension/
   ├─ DEVELOPING.md [1.56 KB]
   ├─ changelog.md [12.09 KB]
   ├─ icon.png [20.09 KB]
   ├─ package.json [16.44 KB]
   ├─ readme.md [4.2 KB]
   ├─ doc-assets/
   │  ├─ complete.png [43.97 KB]
   │  ├─ diagnostics.png [28.87 KB]
   │  ├─ extract.png [20.61 KB]
   │  ├─ format.png [23.39 KB]
   │  ├─ hover.png [60.59 KB]
   │  ├─ include.png [20.58 KB]
   │  ├─ symbolsearch.png [28.74 KB]
   │  └─ xrefs.png [111.77 KB]
   └─ out/
      └─ bundle.js [1007.76 KB]

 DONE  Packaged: /Users/tamird/src/vscode-clangd/vscode-clangd-0.4.0.vsix (16 files, 619.38 KB)
```

**Comment by HighCommander4** [comment]
So I think there are potentially two issues here:

 1. The version of the `vscode-languageclient` dependency in `api/package.json` needs to be bumped to pick up the fix you linked to
 2. Should running `npm run package` at the project root be type-checking things in the `api` subdirectory at all, given that that's a separate package? Can we make it so it doesn't?

**Comment by HighCommander4** [comment]
> Setting the dependency in `api/package.json` to `10.0.0-next.20` **does** fix the errors.

Sent out https://github.com/clangd/vscode-clangd/pull/932 for this.
